name: Taks-1

on:
  workflow_dispatch:
    inputs:
      charts-json:
        description: 'JSON array of chart objects'
        required: true
        default: |
          [
            {
              "chart": "rancher",
              "repository": "https://releases.rancher.com/server-charts/latest",
              "version": "2.8.3"
            },
            {
              "chart": "argo-cd",
              "repository": "https://argoproj.github.io/argo-helm",
              "version": "6.9.2"
            },
            {
              "chart": "grafana",
              "repository": "https://grafana.github.io/helm-charts",
              "version": "7.3.11"
            },
            {
              "chart": "mongodb",
              "repository": "https://charts.bitnami.com/bitnami",
              "version": "15.4.3"
            },
            {
              "chart": "kubernetes-dashboard",
              "repository": "https://kubernetes.github.io/dashboard/",
              "version": "7.3.2"
            },
            {
              "chart": "jenkins",
              "repository": "https://charts.jenkins.io",
              "version": "5.1.17"
            },
            {
              "chart": "nextcloud",
              "repository": "https://nextcloud.github.io/helm/",
              "version": "4.6.6"
            },
            {
              "chart": "pgadmin4",
              "repository": "https://helm.runix.net",
              "version": "1.25.1"
            }
          ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.7.1

    - name: Install Helm S3 plugin
      run: |
        helm plugin install https://github.com/hypnoglow/helm-s3.git

    - name: Set Helm Experimental OCI environment variable
      run: echo "HELM_EXPERIMENTAL_OCI=1" >> $GITHUB_ENV

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Process Helm Charts
      env:
        HELM_REGISTRY_USERNAME: ${{ secrets.HELM_REGISTRY_USERNAME }}
        HELM_REGISTRY_PASSWORD: ${{ secrets.HELM_REGISTRY_PASSWORD }}
      run: |
        charts_json='${{ inputs.charts-json }}'
        echo "$charts_json" | jq -c '.[]' | while read chart; do
          chart_name=$(echo $chart | jq -r '.chart')
          chart_version=$(echo $chart | jq -r '.version')
          repository=$(echo $chart | jq -r '.repository')

          # Adding repository and updating
          helm s3 --force init s3://helm-chart-bucket-sydney/charts/$chart_name
          helm repo add $chart_name s3://helm-chart-bucket-sydney/charts/$chart_name
          helm repo update

          # Pulling the chart from the repository
          mkdir -p /tmp/helm-charts/
          helm fetch $chart_name/$chart_name --version $chart_version -d /tmp/helm-charts
          ls -l /tmp/helm-chart/

          # Pushing the chart to S3
          helm s3 push /tmp/helm-charts/$chart_name-$chart_version.tgz $chart_name
        done

    - name: Clean up temporary directory
      run: |
        rm -rf /tmp/helm-charts
