name: Deploy Helm Chart to S3

on:
  workflow_dispatch:
    inputs:
      chart-name:
        description: 'The name of the Helm chart'
        required: true
        default: 'helm-chart-sonarqube'
      chart-version:
        description: 'The version of the Helm chart'
        required: true
        default: '10.5.1'
      s3-bucket:
        description: 'The S3 bucket to push the Helm chart to'
        required: true
        default: 'my-bucket'
        
permissions:
  contents: read|write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.7.1

    - name: Install Helm S3 plugin
      run: |
        helm plugin install https://github.com/hypnoglow/helm-s3.git

    - name: Set Helm Experimental OCI environment variable
      run: echo "HELM_EXPERIMENTAL_OCI=1" >> $GITHUB_ENV

    - name: Login to Helm registry
      env:
        HELM_EXPERIMENTAL_OCI: 1
        HELM_REGISTRY_USERNAME: ${{ secrets.HELM_REGISTRY_USERNAME }}
        HELM_REGISTRY_PASSWORD: ${{ secrets.HELM_REGISTRY_PASSWORD }}
      run: |
        helm registry login -u $HELM_REGISTRY_USERNAME -p $HELM_REGISTRY_PASSWORD https://artifacthub.io/

    - name: Pull Helm Chart from Registry
      run: |
        mkdir -p /sonarqube
        helm fetch https://SonarSource.github.io/${{ inputs.chart-name }} --version ${{ inputs.chart-version }} -d /sonarqube/
   
    - name: List contents of chart directory
      run: ls -l /sonarqube/

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Initialize Helm S3 repo
      run: |
        helm s3 init s3://helm-chart-bucket-sydney/charts/sonarqube
        helm repo add my-s3-bucket s3://helm-chart-bucket-sydney/charts/sonarqube
        helm repo update

    - name: Push Helm Chart to S3 using Helm with explicit AWS credentials
      run: |
        helm s3 push /sonarqube/${{ inputs.chart-name }}-${{ inputs.chart-version }}.tgz my-bucket

    - name: Clean up temporary directory
      run: |
        rm -rf /helm-chart-sonar
