name: Deploy Helm Chart to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.7.1

    - name: Install Helm S3 plugin
      run: |
        helm plugin install https://github.com/hypnoglow/helm-s3.git
        
    - name: Set Helm Experimental OCI environment variable
      run: echo "HELM_EXPERIMENTAL_OCI=1" >> $GITHUB_ENV

    - name: Login to Helm registry
      env:
        HELM_REGISTRY_USERNAME: ${{ secrets.HELM_REGISTRY_USERNAME }}
        HELM_REGISTRY_PASSWORD: ${{ secrets.HELM_REGISTRY_PASSWORD }}
      run: |
        helm registry login -u $HELM_REGISTRY_USERNAME -p $HELM_REGISTRY_PASSWORD https://artifacthub.io/

    - name: Pull Helm Chart from Registry
      run: |
        helm pull oci://registry-1.docker.io/bitnamicharts/wordpress --version 22.4.12 -d ./chart

    - name: List contents of chart directory
      run: ls -l ./chart

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Initialize Helm S3 repo
      run: |
        helm repo add sydney-bucket s3://helm-chart-bucket-sydney/charts
        helm repo update

    - name: Push Helm Chart to S3 using Helm
      run: |
        helm s3 push ./chart/wordpress-22.4.12.tgz sydney-bucket
