name: Upload Helm Chart

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: List Helm chart packages
      run: ls -l helm-chart/*.tgz

    - name: Upload Helm chart to S3
      run: |
        for file in helm-chart/*.tgz; do
          echo "Uploading $file to s3://helm-chart-1997/charts/"
          aws s3 cp "$file" "s3://helm-chart-1997/charts/"
        done
