name: Deploy Helm Chart

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Package Helm chart
      run: helm package ./helm-chart

    - name: List packaged Helm chart
      run: ls -l *.tgz

    - name: Upload Helm chart to S3
      run: |
        CHART_PACKAGE=$(ls *.tgz)
        echo "Uploading $CHART_PACKAGE to s3://helm-chart-1997/charts/"
        aws s3 cp $CHART_PACKAGE s3://helm-chart-1997/charts/
