name: Upload Helm Chart to S3

on:
  push:
    branches:
      - main

jobs:
  upload-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload Helm chart artifact
        uses: actions/upload-artifact@v2
        with:
          name: helm-chart
          path: path/to/your/local/helm/chart/*.tgz

      - name: Download Helm chart artifact
        uses: actions/download-artifact@v2
        with:
          name: helm-chart
          path: ./helm-chart

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: <ap-southeast-2>
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_DEFAULT_REGION

      - name: Upload chart to S3
        run: |
          aws s3 cp ./helm-chart/*.tgz s3://helm-chart-1997/charts
